name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Fetch main branch
        run: git fetch origin main:main
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - uses: nrwl/nx-set-shas@v4
        with:
            main-branch-name: main
      - run: pnpm nx affected -t lint build
